import Head from 'next/head'
import { useSession, signOut } from 'next-auth/react'
import Link from 'next/link'

import type { NextPageWithAuth } from '../types'

const Home: NextPageWithAuth = () => {
  const { data: session } = useSession()

  const handleSignOut = async () => {
    signOut({ callbackUrl: '/auth/signin' })
  }

  return (
    <>
      <Head>
        <title>Next auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid place-content-center min-h-screen space-y-2">
        <div>email: {session?.user.email}</div>
        <button
          className="py-1 border text-center rounded transition hover:bg-orange-500 hover:text-white"
          onClick={handleSignOut}
        >
          sign out
        </button>
        <Link href="/profile" passHref>
          <a className="py-1 border text-center rounded transition hover:bg-emerald-500 hover:text-white">
            Profile
          </a>
        </Link>
      </div>
    </>
  )
}

Home.auth = true

export default Home
