import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useSession } from 'next-auth/react'

import type { NextPageWithAuth } from '../types'

const Profile: NextPageWithAuth = () => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Next auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>{session?.user?.email}</ul>
      <div className="mt-2">
        <Link href="/" passHref>
          <a className="py-1 border text-center rounded transition hover:bg-emerald-500 hover:text-white px-2">
            Home
          </a>
        </Link>
      </div>
    </>
  )
}

Profile.auth = true

export default Profile
